name: Publish

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform: [ Win32, x64 ]
        configuration: [ Release ]
    runs-on: windows-latest

    steps:
      
    - name: Set DirectX SDK Path
      shell: bash
      run: echo ::set-env name=DXSDK_DIR::$HOME/cache/
      
    - name: Cache
      id:   cache
      uses: actions/cache@v1
      with:
       path: ~/cache
       key:  cache
       
    - name: Create create
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
       curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
       7z x _DX2010_.exe DXSDK/Include -o_DX2010_
       7z x _DX2010_.exe DXSDK/Lib/x86 -o_DX2010_
       mv _DX2010_/DXSDK $HOME/cache
       rm -fR _DX*_ _DX*_.exe
      shell: bash

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Clone
      shell: bash
      run: git clone --recurse-submodules https://github.com/Bartis1313/csgo
        
    - name: Build solution
      working-directory: ./csgo
      env:
        SOLUTION_FILE_PATH: ./csgo-legit.sln
        BUILD_CONFIGURATION: Release
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
        
    - name: Removing unused files
      shell: bash
      run: |
        rm -rf ./csgo/build/${{ matrix.platform }}/${{ matrix.configuration }}/obj
        rm -rf ./csgo/build/${{ matrix.platform }}/${{ matrix.configuration }}/*.pdb
        rm -rf ./csgo/build/${{ matrix.platform }}/${{ matrix.configuration }}/*.obj
      
    - name: Upload latest artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: csgo-${{ matrix.platform }}-${{ matrix.configuration }}
        path: ./csgo/build/${{ matrix.platform }}/${{ matrix.configuration }}/*
        if-no-files-found: error
